name: Android CI

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode keystore file
      run: echo "${{ secrets.REDLINE_RELEASE_KEY }}" | base64 --decode > redline-release-key.jks

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore redline-release-key.jks -storepass ${{ secrets.REDLINE_RELEASE_KEY_SECRET }} app/build/outputs/apk/release/app-release-unsigned.apk alias_name

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: ./app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Create Tag
      run: |
        echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        git tag ${{ env.TAG }}
        git push origin ${{ env.TAG }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG }}
        release_name: Release ${{ env.TAG }}

    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: redline-release.apk
        asset_content_type: application/vnd.android.package-archive
